name: 'Deploy blocklet'
description: 'Deploy blocklet to abtnode'
inputs:
  endpoint:
    description: 'Endpoint of abtnode'
    required: true
  access-key:
    description: 'Access key of abtnode'
    required: true
  access-secret:
    description: 'Access secret of abtnode'
    required: true
  slack-webhook:
    description: 'Webhook of slack'
    required: false
  app-did:
    description: 'Deploy as a app child blocklet'
    required: false
  mount-point:
    description: 'If is a child blocklet, need setup a mount point'
    required: false
  folder-path:
    description: '.blocklet/bundle path'
    default: .blocklet/bundle
    required: false
  working-directory:
    description: 'Working directory'
    default: ./
    required: false
  skip:
    description: 'Skip action'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
